name: Release Please

on:
  push:
    branches:
      - master

jobs:
  release:
    name: release
    runs-on: ubuntu-latest
    steps:
      - uses: google-github-actions/release-please-actio@v3
        with:
          release-type: simple
          package-name: daylight.nvim
